agrego una listita
rodrigo-reynoso/ropa-para-mi pull request #4
Opened 2020-06-24 18:15 UTC by juanpabloisabella

hice este cambio, saludos.

2020-06-24 18:18 UTC, juanpabloisabella commented on index.html
> +        <li>se feliz
me olvide de cerrar el tag <li></li> ):

2020-06-24 18:19 UTC, juanpabloisabella commented on index.html
> +        </li>
y este quedo suelto

2020-06-24 19:18 UTC, rnfanego requested changes
En general el que solicita review deja una descripcion de su cambio, y los reviewers dejan los comentarios.  Vos directamente pushea fixes sobre tu branch.
Al pull request se le suelen agregar los reviewers ya cuando la tarea esta terminada o casi terminada

2020-06-24 22:45 UTC, rodrigo-reynoso approved these changes
Me parece bien, como para empezar,  con este viaje de commit !!!!!

2020-06-24 22:45 UTC, rodrigo-reynoso commented on index.html
> +        </li>
ahi tenes el que te falta en la linea 13

2020-06-24 22:45 UTC, rodrigo-reynoso commented on index.html
> +        </li>
Estaba viendo como es el reviewing proposed changes in a pull request

2020-06-25 00:26 UTC, juanpabloisabella commented
> En general el que solicita review deja una descripcion de su cambio, y los reviewers dejan los comentarios.  Vos directamente pushea fixes sobre tu branch.
> Al pull request se le suelen agregar los reviewers ya cuando la tarea esta terminada o casi terminada

Entendido!

2020-07-23 20:47 UTC, closed without merging