agregue pagina uno y dos
rodrigo-reynoso/ropa-para-mi pull request #5
Opened 2020-07-12 06:24 UTC by rodrigo-reynoso

Hice un poco de diseño en la pagina 1 y 2, es mi  tarea de coding. Si le gusta el diseño del logo se podria hacer en css pero llevaria tiempo, sería una tarea aparte. Bueno hay cosillas por modificar y mejorer.... espero que les guste

2020-07-12 16:48 UTC, rnfanego commented on hoja2.html
> +<!DOCTYPE html>
Que el nombre de la pagina refleje lo que hace (busqueda.html o algo así)

2020-07-12 16:49 UTC, rnfanego commented on estilohoja2.css
> +* {
que el estilo refleje a que pagina pertenece (podriamos tener algun tipo de convencion, por ejemplo estilo-nombreDeLaPagina.html, en este caso seria algo como estilo-busqueda.css

2020-07-12 16:50 UTC, rnfanego commented on estilos.css
> +body {
Lo mismo para el nombre de este css

2020-07-12 16:51 UTC, rnfanego commented on hoja2.html
> +      <div class="logo-segunda-pagina"><h1>ROPA PARA MI</h1></div>
El header lo vamos a reutilizar en otras paginas (detalle de tienda, registracion/ingreso) por lo que estaría bueno sacarlo en otro html y llamarlo sin repetir el codigo en todas las paginas.

2020-07-12 16:52 UTC, rnfanego commented on estilohoja2.css
> +  margin: 0;
La revisión del css se la dejo a @kalaniz0018 que lo tiene más fresco

2020-07-12 16:53 UTC, rnfanego commented on index.html
> +  <head>
El testing de la página ya lo podés empezar a ver vos @juanpabloisabella, al menos temas de estilo que se ven mal y cuestiones de usabilidad.  Luego vemos de hacer alguna prueba automatizada

2020-07-12 16:54 UTC, rnfanego commented on .gitignore
> +# -----------------------------------------------------------------
Este archivo .gitignore lo saqué de https://gist.github.com/salcode/10017553, en la reunión de planificación hablo un poco de esto.

2020-07-12 16:57 UTC, rnfanego commented on index.html
> +        <img class="logo" src="oie_1061334oSpBJr73.png" alt="" />
Ponerle nombre significativo al logo

2020-07-12 16:58 UTC, rnfanego requested changes
Te dejé algunos comentarios, principalmente relacionado al nombrado de archivos.

2020-07-12 19:11 UTC, juanpabloisabella commented on index.html
> +  <head>
Listo, perfecto.

2020-07-12 19:13 UTC, juanhu9999 approved these changes

2020-07-18 23:16 UTC, rnfanego approved these changes

2020-07-22 23:18 UTC, rnfanego commented on index.html
> +      <div class="container-logo">
asdfasfdasdf

2020-08-05 21:37 UTC, kalaniz0018 approved these changes

2020-08-05 22:51 UTC, merged